### ISSUE TITLE
Feature - Consider using puppet_pal

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-editor-services#61]
Henrik has released a blog on a simplier way to use the Puppet library

https://puppet-on-the-edge.blogspot.com/2018/10/puppet-pal-wants-to-be-your-friend.html

Would we consider using this?

It would probably mean dropping Puppet 4 support.

**Comment by hlindberg** [comment]
Also note, that PAL was introduced late in puppet 5.y series, but then only supporting the "scripting" mode. This was for Bolt. The CatalogCompiler support is from Puppet 6.0.0.
It would be possible to backport the CatalogCompiler to 5, or even to 4 - with the exception that Puppet 4 on older rubies would not work since PAL uses named arguments.

**Comment by glennsarti** [comment]
Now that Puppet4 is EOL, it may be time to seriously consider using PAL instead of full puppet for AST generation.  It would prevent some of the `Puppet[:tasks]` setting switching sheningans I'm doing.

**Comment by glennsarti** [comment]
Closing. The new puppet-strings feature flag uses components of Puppet PAL.
